[package]
name = "rtd-macros"
version = "0.7.0"
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
rtd-proc-macros.workspace = true
once_cell.workspace = true
futures.workspace = true
tracing.workspace = true
