[package]
name = "rtd-indexer-alt-e2e-tests"
version = "0.1.0"
authors = ["LinkU Labs <eng@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[[test]]
name = "transactional_tests"
harness = false

[dependencies]
anyhow.workspace = true
bcs.workspace = true
diesel = { workspace = true, features = ["chrono"] }
diesel-async = { workspace = true, features = ["bb8", "postgres", "async-connection-wrapper"] }
fastcrypto.workspace = true
prometheus.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
shared-crypto.workspace = true
tempfile.workspace = true
tokio.workspace = true
url.workspace = true

simulacrum.workspace = true
rtd-futures.workspace = true
rtd-indexer-alt.workspace = true
rtd-indexer-alt-consistent-api.workspace = true
rtd-indexer-alt-consistent-store.workspace = true
rtd-indexer-alt-framework = { workspace = true, features = ["postgres", "cluster"] }
rtd-indexer-alt-graphql.workspace = true
rtd-indexer-alt-jsonrpc.workspace = true
rtd-indexer-alt-reader.workspace = true
rtd-indexer-alt-schema.workspace = true
rtd-pg-db.workspace = true
rtd-storage.workspace = true
rtd-types.workspace = true
move-core-types.workspace = true
rtd-move-build.workspace = true

[target.'cfg(msim)'.dependencies]
msim.workspace = true
rtd-protocol-config.workspace = true
rtd-simulator.workspace = true
tracing.workspace = true

[dev-dependencies]
async-trait.workspace = true
datatest-stable.workspace = true
insta.workspace = true
jsonrpsee.workspace = true
telemetry-subscribers.workspace = true
tonic.workspace = true

rtd-field-count.workspace = true
rtd-json-rpc-types.workspace = true
rtd-macros.workspace = true
rtd-sdk.workspace = true
rtd-swarm-config.workspace = true
rtd-test-transaction-builder.workspace = true
rtd-transactional-test-runner.workspace = true
test-cluster.workspace = true
tracing.workspace = true
