[package]
name = "rtd-package-alt"
version.workspace = true
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
bin-version.workspace = true
anyhow.workspace = true
clap.workspace = true
indexmap.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-package-alt.workspace = true
move-package-alt-compilation.workspace = true
serde.workspace = true
rtd-package-management.workspace = true
shared-crypto.workspace = true
rtd-config.workspace = true
rtd-sdk.workspace = true
rtd-json-rpc-types.workspace = true
rtd-keys.workspace = true
tokio.workspace = true
tracing.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true
