[package]
name = "rtd-kvstore"
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
bcs.workspace = true
clap.workspace = true
http.workspace = true
gcp_auth.workspace = true
prometheus.workspace = true
prost.workspace = true
prost-types.workspace = true
serde.workspace = true
rtd-data-ingestion-core.workspace = true
rtd-types.workspace = true
telemetry-subscribers.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true, features = ["transport"] }
tonic-prost.workspace = true
tracing.workspace = true
