[package]
name = "typed-store-derive"
version = "0.3.0"
license = "Apache-2.0"
authors = ["Ade A. <ade@linkulabs.com>"]
description = "macros for the typed-store crate"
repository = "https://github.com/linkulabs/linku-infra"
edition = "2024"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
itertools.workspace = true
