[package]
name = "rtd-oracle"
version.workspace = true
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
clap.workspace = true
prometheus = "0.13.3"
tokio = { workspace = true, features = ["full"] }
tracing = "0.1.36"
once_cell.workspace = true
reqwest.workspace = true
serde = { version = "1.0.144", features = ["derive", "rc"] }
serde_json = { version = "1.0.1" }
jsonpath_lib = "0.3.0"
chrono.workspace = true
tap.workspace = true
bcs.workspace = true

rtd-config.workspace = true
rtd-json-rpc-types.workspace = true
rtd-sdk.workspace = true
rtd-types.workspace = true
linku-metrics.workspace = true
telemetry-subscribers.workspace = true

[dev-dependencies]
rtd-keys.workspace = true
rtd-move-build.workspace = true
shared-crypto.workspace = true
bcs = "0.1.5"
rand = "0.8.5"
dirs = "4.0.0"
