[package]
name = "rtd-adapter-v2"
version = "0.1.0"
authors = ["LinkU Labs <eng@linkulabs.com>"]
description = "Adapter and accompanying CLI for local rtd development"
license = "Apache-2.0"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
bcs.workspace = true
leb128.workspace = true
tracing.workspace = true
serde.workspace = true

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true

move-bytecode-verifier = { path = "../../../external-crates/move/move-execution/v2/crates/move-bytecode-verifier", package = "move-bytecode-verifier-v2" }
move-vm-runtime = { path = "../../../external-crates/move/move-execution/v2/crates/move-vm-runtime", package = "move-vm-runtime-v2" }
move-vm-profiler = { path = "../../../external-crates/move/crates/move-vm-profiler" }
rtd-move-natives = { path = "../rtd-move-natives", package = "rtd-move-natives-v2" }
rtd-verifier = { path = "../rtd-verifier", package = "rtd-verifier-v2" }
move-vm-types = { path = "../../../external-crates/move/move-execution/v2/crates/move-vm-types", package = "move-vm-types-v2" }

rtd-macros.workspace = true
rtd-protocol-config.workspace = true
rtd-types.workspace = true
parking_lot.workspace = true

[features]
tracing = [
    "rtd-types/tracing",
    "move-vm-runtime/tracing",
    "move-vm-profiler/tracing",
    "move-vm-config/tracing",
]
