[package]
name = "rtd-indexer"
version.workspace = true
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
rand = "0.8.5"
async-trait.workspace = true
axum.workspace = true
backon.workspace = true
bb8 = "0.8.5"
bcs.workspace = true
bytes.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["env"] }
csv.workspace = true
diesel = { workspace = true, features = ["chrono", "serde_json"] }
diesel-async = { workspace = true, features = ["bb8", "postgres", "async-connection-wrapper"] }
futures.workspace = true
hex.workspace = true
indicatif.workspace = true
itertools.workspace = true
jsonrpsee.workspace = true
object_store.workspace = true
prometheus.workspace = true
rayon.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
strum.workspace = true
strum_macros.workspace = true
tap.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["rt"] }
toml.workspace = true
tracing.workspace = true
url.workspace = true

fastcrypto = { workspace = true, features = ["copy_key"] }
linku-metrics.workspace = true
simulacrum.workspace = true
rtd-config.workspace = true
rtd-core.workspace = true
rtd-data-ingestion-core.workspace = true
rtd-json.workspace = true
rtd-json-rpc.workspace = true
rtd-json-rpc-api.workspace = true
rtd-json-rpc-types.workspace = true
rtd-name-service.workspace = true
rtd-open-rpc.workspace = true
rtd-pg-db.workspace = true
rtd-sdk.workspace = true
rtd-snapshot.workspace = true
rtd-storage.workspace = true
rtd-types.workspace = true
rtd-package-resolver.workspace = true
rtd-protocol-config.workspace = true
telemetry-subscribers.workspace = true
rtd-rpc-api.workspace = true
rtd-transaction-builder.workspace = true

move-core-types.workspace = true
move-bytecode-utils.workspace = true
move-binary-format.workspace = true

diesel_migrations.workspace = true
cached.workspace = true
tokio-stream.workspace = true
dashmap.workspace = true

[dev-dependencies]
rtd-keys.workspace = true
rtd-move-build.workspace = true
rtd-swarm-config.workspace = true
rtd-test-transaction-builder.workspace = true
test-cluster.workspace = true

[[bin]]
name = "rtd-indexer"
path = "src/main.rs"
