[package]
name = "rtd-indexer-builder"
version = "0.1.0"
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
tap.workspace = true
tokio = { workspace = true, features = ["full"] }
async-trait.workspace = true
linku-metrics.workspace = true
rtd-types.workspace = true
rtd-sdk.workspace = true
rtd-data-ingestion-core.workspace = true
futures.workspace = true
tracing.workspace = true
prometheus.workspace = true
telemetry-subscribers.workspace = true

[dev-dependencies]
rtd-indexer-builder = { workspace = true, features = ["test-utils"] }

[features]
test-utils = []
