[package]
name = "rtd-replay-2"
version = "0.1.0"
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bcs.workspace = true
bin-version.workspace = true
clap.workspace = true
chrono.workspace = true
csv.workspace = true
fastcrypto.workspace = true
futures.workspace = true
move-binary-format.workspace = true
move-bytecode-source-map.workspace = true
move-cli.workspace = true
move-command-line-common.workspace = true
move-core-types.workspace = true
move-disassembler.workspace = true
move-ir-types.workspace = true
move-package-alt.workspace = true
move-package-alt-compilation.workspace = true
move-trace-format.workspace = true
prometheus.workspace = true
serde.workspace = true
similar.workspace = true
rtd-config.workspace = true
rtd-data-store.workspace = true
rtd-execution.workspace = true
rtd-framework.workspace = true
rtd-json-rpc-types.workspace = true
rtd-move.workspace = true
rtd-move-build.workspace = true
rtd-package-management.workspace = true
rtd-types.workspace = true
serde_json.workspace = true
tabled.workspace = true
rtd-package-alt.workspace = true
telemetry-subscribers.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
toml.workspace = true
tracing.workspace = true
zstd.workspace = true
indicatif.workspace = true

[features]
tracing = [
    "rtd-types/tracing",
    "rtd-execution/tracing",
]
