[package]
name = "rtd-graphql-rpc"
version.workspace = true
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"


[dependencies]
anyhow.workspace = true
async-graphql = {workspace = true, features = ["dataloader", "apollo_tracing", "tracing"] }
async-graphql-axum.workspace = true
async-graphql-value.workspace = true
async-trait.workspace = true
# axum.workspace = true
# axum-extra.workspace = true
axum = { version = "0.7", default-features = false, features = [ "macros", "tokio", "http1", "http2", "json", "matched-path", "original-uri", "form", "query", "ws", ] }
axum-extra = { version = "0.9", features = ["typed-header"] }
bin-version.workspace = true
chrono.workspace = true
clap.workspace = true
const-str.workspace = true
diesel = { workspace = true, features = ["i-implement-a-third-party-backend-and-opt-into-breaking-changes"] }
diesel-async = { workspace = true, features = ["postgres"] }
either.workspace = true
fastcrypto = { workspace = true, features = ["copy_key"] }
fastcrypto-zkp.workspace = true
futures.workspace = true
hex.workspace = true
http.workspace = true
hyper.workspace = true
itertools.workspace = true
lru.workspace = true
move-binary-format.workspace = true
move-disassembler.workspace = true
move-ir-types.workspace = true
linku-metrics.workspace = true
linku-network.workspace = true
move-core-types.workspace = true
once_cell.workspace = true
prometheus.workspace = true
rand.workspace = true # todo: cleanup test only deps
regex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
shared-crypto.workspace = true
similar.workspace = true
rtd-display.workspace = true
rtd-name-service.workspace = true
rtd-pg-db.workspace = true
rtd-sdk.workspace = true
rtd-types.workspace = true
tap.workspace = true
telemetry-subscribers.workspace = true
tempfile.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tokio-util = { workspace = true, features = ["rt"] }
toml.workspace = true
tower.workspace = true
tower-http.workspace = true
thiserror.workspace = true
uuid.workspace = true
im.workspace = true
downcast = "0.11.0"

rtd-default-config.workspace = true
rtd-graphql-rpc-headers.workspace = true
rtd-graphql-rpc-client.workspace = true

# TODO: put these behind feature flag to prevent leakage
# Used for dummy data
bcs.workspace = true
simulacrum.workspace = true  # todo: cleanup test only deps
rtd-json-rpc.workspace = true
rtd-json-rpc-types.workspace = true
rtd-indexer.workspace = true
rtd-rpc-api.workspace = true
rtd-swarm-config.workspace = true
test-cluster.workspace = true
rtd-protocol-config.workspace = true
move-bytecode-utils.workspace = true
rtd-package-resolver.workspace = true

[dev-dependencies]
expect-test.workspace = true
hyper.workspace = true
insta.workspace = true
serde_json.workspace = true
rtd-framework.workspace = true
tower.workspace = true
rtd-test-transaction-builder.workspace = true
rtd-move-build.workspace = true

[features]
staging = []
