[package]
name = "rtd-graphql-rpc-headers"
version = "0.1.0"
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
axum.workspace = true
