[package]
name = "rtd-indexer-alt-framework"
version.workspace = true
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
backoff.workspace = true
bb8 = "0.8.5"
bytes.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["env"] }
diesel = { workspace = true, features = ["chrono"] }
diesel-async = { workspace = true, features = ["bb8", "postgres", "async-connection-wrapper"] }
diesel_migrations.workspace = true
futures.workspace = true
pin-project-lite.workspace = true
prometheus.workspace = true
reqwest.workspace = true
scoped-futures.workspace = true
serde.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, optional = true }
url.workspace = true

rtd-field-count.workspace = true
rtd-futures.workspace = true
rtd-indexer-alt-framework-store-traits.workspace = true
rtd-indexer-alt-metrics.workspace = true
rtd-rpc.workspace = true
rtd-sdk-types.workspace = true
rtd-rpc-api.workspace = true
rtd-storage.workspace = true
rtd-types.workspace = true
prost-types.workspace = true

rtd-pg-db = { workspace = true, optional = true }

[dev-dependencies]
rand.workspace = true
telemetry-subscribers.workspace = true
wiremock.workspace = true
rtd-pg-db.workspace = true
dashmap.workspace = true

rtd-synthetic-ingestion.workspace = true

[features]
default = ["cluster"]
cluster = ["dep:tracing-subscriber", "postgres"]
postgres = ["dep:rtd-pg-db"]
