[package]
name = "rtd-json-rpc-api"
version = "0.0.0"
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
jsonrpsee.workspace = true
once_cell.workspace = true
prometheus.workspace = true
tap.workspace = true
tracing.workspace = true
fastcrypto.workspace = true
linku-metrics.workspace = true
rtd-json.workspace = true
rtd-json-rpc-types.workspace = true
rtd-open-rpc.workspace = true
rtd-open-rpc-macros.workspace = true
rtd-types.workspace = true

# NOTE: It's important to keep the above dependency list short.
# This and the rtd-sdk crate are widely used to develop on Rtd and it's valuable
# to not have to pull in the entire rtd repo for it.

[dev-dependencies]
