[package]
name = "rtd-json-rpc-tests"
version = "0.0.0"
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]

[dev-dependencies]
move-core-types.workspace = true
rtd-config.workspace = true
rtd-core.workspace = true
rtd-keys.workspace = true
rtd-move-build.workspace = true
rtd-test-transaction-builder.workspace = true
rtd-sdk.workspace = true
rtd-macros.workspace = true
rtd-simulator.workspace = true
rtd-json.workspace = true
rtd-json-rpc.workspace = true
rtd-json-rpc-api.workspace = true
rtd-json-rpc-types.workspace = true
rtd-open-rpc.workspace = true
rtd-open-rpc-macros.workspace = true
rtd-protocol-config.workspace = true
rtd-swarm-config.workspace = true
rtd-types.workspace = true
test-cluster.workspace = true
telemetry-subscribers.workspace = true

anyhow.workspace = true
async-trait.workspace = true
bcs.workspace = true
hyper.workspace = true
jsonrpsee.workspace = true
prometheus.workspace = true
rand.workspace = true
reqwest.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
shared-crypto.workspace = true
