[package]
name = "rtd-field-count"
version.workspace = true
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
rtd-field-count-derive.workspace = true
