[package]
name = "rtd-tool"
version.workspace = true
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
num_cpus.workspace = true
bcs.workspace = true
clap = { version = "4.1.4", features = ["derive"] }
colored.workspace = true
comfy-table.workspace = true
eyre.workspace = true
futures.workspace = true
hex.workspace = true
move-core-types.workspace = true
itertools.workspace = true
ron.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
tempfile.workspace = true
tracing.workspace = true
prometheus.workspace = true
object_store.workspace = true
indicatif.workspace = true
consensus-core.workspace = true
linku-metrics.workspace = true

anemo-cli.workspace = true
anemo.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full"] }
typed-store.workspace = true
fastcrypto.workspace = true

rtd-config.workspace = true
rtd-core.workspace = true
rtd-data-ingestion-core.workspace = true
rtd-network.workspace = true
rtd-snapshot.workspace = true
rtd-protocol-config.workspace = true
rtd-replay.workspace = true
rtd-sdk.workspace = true
rtd-storage.workspace = true
rtd-types.workspace = true
rtd-package-dump.workspace = true
rtd-tls.workspace = true
bin-version.workspace = true
