[package]
name = "transaction-fuzzer"
version = "0.1.0"
edition = "2024"
authors = ["LinkU Labs <eng@linkulabs.com>"]
description = "Tool to fuzz the system with randomly generated transactions"
license = "Apache-2.0"
publish = false

[lints]
workspace = true

[dependencies]
proptest.workspace = true
proptest-derive.workspace = true
rand.workspace = true
move-core-types.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true

once_cell.workspace = true
rtd-core.workspace = true
rtd-protocol-config.workspace = true
rtd-types = { workspace = true, features = ["fuzzing"] }
rtd-move-build.workspace = true


[dev-dependencies]
rtd-protocol-config.workspace = true
