[package]
name = "rtd-transactional-test-runner"
version = "0.1.0"
edition = "2024"
authors = ["LinkU Labs <eng@linkulabs.com>"]
description = "Move framework for Rtd platform"
license = "Apache-2.0"
publish = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bcs.workspace = true
bimap.workspace = true
bincode = { version = "2.0.1", features = ["serde"] }
clap.workspace = true
eyre.workspace = true
http.workspace = true
once_cell.workspace = true
rand.workspace = true
regex.workspace = true
tempfile.workspace = true
async-trait.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
criterion.workspace = true
tracing.workspace = true
winnow.workspace = true

fastcrypto.workspace = true
fastcrypto-zkp.workspace = true
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-symbol-pool.workspace = true
move-transactional-test-runner.workspace = true
telemetry-subscribers.workspace = true
iso8601.workspace = true

move-stdlib = { path = "../../external-crates/move/crates/move-stdlib" }
move-vm-runtime = { path = "../../external-crates/move/crates/move-vm-runtime" }

simulacrum.workspace = true
rtd-graphql-rpc.workspace = true
rtd-rpc-api.workspace = true
rtd-swarm-config.workspace = true
rtd-config.workspace = true
rtd-core.workspace = true
rtd-framework.workspace = true
rtd-protocol-config.workspace = true
rtd-types.workspace = true
rtd-json-rpc-types.workspace = true
rtd-json-rpc.workspace = true
rtd-json-rpc-api.workspace = true
rtd-framework-snapshot.workspace = true
rtd-storage.workspace = true
typed-store.workspace = true

[target.'cfg(msim)'.dependencies]
msim.workspace = true
