[package]
name = "rtd-package-management"
version.workspace = true
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true

rtd-json-rpc-types.workspace = true
rtd-sdk.workspace = true
rtd-types.workspace = true
rtd-protocol-config.workspace = true

move-core-types.workspace = true
move-symbol-pool.workspace = true

[build-dependencies]
rtd-framework-snapshot.workspace = true
anyhow.workspace = true
