[package]
name = "rtd-single-node-benchmark"
version.workspace = true
edition = "2024"
publish = false
license = "Apache-2.0"

[dependencies]
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-core-types.workspace = true
move-symbol-pool.workspace = true
rtd-config.workspace = true
rtd-core.workspace = true
rtd-move-build.workspace = true
rtd-test-transaction-builder.workspace = true
rtd-transaction-checks.workspace = true
rtd-types.workspace = true
rtd-storage.workspace = true

async-trait.workspace = true
bcs.workspace = true
clap.workspace = true
futures.workspace = true
prometheus.workspace = true
once_cell.workspace = true
serde = { version = "1.0.190", features = ["derive"] }
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full", "tracing", "test-util"] }
tracing.workspace = true

[dev-dependencies]
rtd-macros.workspace = true
rtd-protocol-config.workspace = true
rtd-simulator.workspace = true
