[package]
name = "rtd-rosetta"
version.workspace = true
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
axum.workspace = true
axum-extra.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
futures.workspace = true
once_cell.workspace = true
signature.workspace = true
bcs.workspace = true
hyper.workspace = true
strum.workspace = true
strum_macros.workspace = true
async-trait.workspace = true
clap.workspace = true
thiserror.workspace = true
eyre.workspace = true
tempfile.workspace = true
fastcrypto.workspace = true
rtd-types.workspace = true
rtd-config.workspace = true
rtd-keys.workspace = true
rtd-rpc.workspace = true
rtd-sdk-types.workspace = true
linku-metrics.workspace = true
shared-crypto.workspace = true
lru.workspace = true
tonic.workspace = true
prost-types.workspace = true
chrono.workspace = true

move-core-types.workspace = true

telemetry-subscribers.workspace = true
enum_dispatch.workspace = true

[dev-dependencies]
rtd-swarm-config.workspace = true
rtd-sdk.workspace = true
rtd-move-build.workspace = true
rtd-test-transaction-builder.workspace = true
test-cluster.workspace = true
tempfile.workspace = true
rand.workspace = true
reqwest.workspace = true
move-cli.workspace = true
quick-js = "0.4.1"
