[package]
name = "rtd-graphql-e2e-tests"
version = "0.1.0"
authors = ["LinkU Labs <eng@linkulabs.com>"]
description = "End to end tests for Rtd GraphQL"
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dev-dependencies]
anyhow.workspace = true
async-trait.workspace = true
telemetry-subscribers.workspace = true
datatest-stable.workspace = true
serde_json.workspace = true
rtd-graphql-rpc.workspace = true
rtd-transactional-test-runner.workspace = true
tokio.workspace = true

[[test]]
name = "tests"
harness = false

[dependencies]

[target.'cfg(msim)'.dependencies]
msim.workspace = true

[features]
staging = ["rtd-graphql-rpc/staging"]
