[package]
name = "rtd-open-rpc"
version.workspace = true
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
bcs.workspace = true
versions.workspace = true

[dev-dependencies]
anyhow.workspace = true
clap.workspace = true
pretty_assertions.workspace = true
tokio = { workspace = true, features = ["full"] }
fastcrypto.workspace = true
rtd-json-rpc.workspace = true
rtd-json-rpc-api.workspace = true
rtd-json-rpc-types.workspace = true
rtd-json.workspace = true
rtd-types.workspace = true
rtd-protocol-config.workspace = true
rand.workspace = true

move-core-types.workspace = true

[[example]]
name = "generate-json-rpc-spec"
path = "src/generate_json_rpc_spec.rs"
test = false
