---
version: "3.9"
services:
  fullnode:
    # Note: Update the tag to the latest version of linku/rtd-node for mainnet or testnet.
    image: linku/rtd-node:mainnet-v1.19.1
    ports:
    - "8080:8080"
    - "8084:8084/udp"
    - "9000:9000"
    - "9184:9184"
    volumes:
    - ./fullnode-template.yaml:/opt/rtd/config/fullnode.yaml:ro
    - ./genesis.blob:/opt/rtd/config/genesis.blob:ro
    - ./rtddb:/opt/rtd/db:rw
    command: ["/opt/rtd/bin/rtd-node", "--config-path", "/opt/rtd/config/fullnode.yaml"]
volumes:
  rtddb:
