[package]
name = "rtdns-indexer"
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"
version.workspace = true

[dependencies]
diesel = { workspace = true, features = ["serde_json"] }
diesel-async = { workspace = true, features = ["bb8", "postgres"] }
rtd-data-ingestion-core.workspace = true
anyhow.workspace = true
async-trait.workspace = true
backoff.workspace = true
base64-url.workspace = true
bcs.workspace = true
bytes.workspace = true
futures.workspace = true
linku-metrics.workspace = true
object_store.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
prometheus.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
rtd-name-service.workspace = true
rtd-storage.workspace = true
rtd-types.workspace = true
url.workspace = true
dotenvy = "0.15"
move-core-types.workspace = true
linku-service.workspace = true
rustls.workspace = true
webpki-roots = "0.26.3"
tokio-postgres-rustls = "0.12.0"
tokio-postgres = "0.7.12"
futures-util = "0.3.30"

[dev-dependencies]
rand.workspace = true
tempfile.workspace = true
