[package]
name = "Bridge"
version = "0.0.1"
published-at = "0xb"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
Rtd = { local = "../rtd-framework" }
RtdSystem = { local = "../rtd-system" }

[addresses]
bridge = "0xb"

