[package]
name = "bls_signature"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Rtd = { local = "../../../../crates/rtd-framework/packages/rtd-framework" }

[addresses]
bls_signature = "0x0"
