[package]
name="regulated_coin_example"
version="0.0.1"
edition="2024"

[dependencies]
# Starting with Rtd 1.45, dependencies on system packages are no longer required.
Rtd = { local = "../../../crates/rtd-framework/packages/rtd-framework" }

[addresses]
regulated_coin_example="0x0"
