[package]
name = "move-vm-profiler"
version = "0.1.0"
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
once_cell.workspace = true
tracing.workspace = true

move-trace-format.workspace = true
move-vm-config.workspace = true

[features]
tracing = ["move-vm-config/tracing"]
