[package]
name = "rtd-kv-rpc"
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"
version.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
bin-version.workspace = true
clap.workspace = true
prometheus.workspace = true
linku-metrics.workspace = true
linku-network.workspace = true
rtd-data-ingestion-core.workspace = true
rtd-kvstore.workspace = true
rtd-rpc-api.workspace = true
rtd-rpc.workspace = true
rtd-types.workspace = true
rtd-sdk-types.workspace = true
telemetry-subscribers.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-reflection.workspace = true
tracing.workspace = true
rtd-protocol-config.workspace = true
