[package]
name = "rtd-telemetry"
version = "0.1.0"
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
serde.workspace = true
reqwest.workspace = true
tracing.workspace = true

rtd-core.workspace = true
