[package]
name = "BridgedKa"
version = "0.0.1"
edition = "legacy"

[dependencies]
MoveStdlib = { local = "../../../../../crates/rtd-framework/packages/move-stdlib" }
Rtd = { local = "../../../../../crates/rtd-framework/packages/rtd-framework" }

[addresses]
bridged_ka = "0x0"
