[package]
name = "linku-service-boilerplate"
authors = ["LinkU Labs <build@linkulabs.com>"]
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.79"
axum = { version = "0.7", features = ["macros"] }
linku-service = { git = "https://github.com/linkulabs/rtd.git", branch = "main", package = "linku-service" }
prometheus = "0.13.3"
tracing = "0.1.40"
serde = { version = "1.0.188", features = ["derive"] }
tokio = { version = "1.32.0", features = ["full"] }
