[package]
name = "rtd"
version.workspace = true
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
anemo.workspace = true
anyhow.workspace = true
async-recursion.workspace = true
async-trait.workspace = true
aws-config.workspace = true
aws-sdk-kms.workspace = true
axum.workspace = true
bcs.workspace = true
bin-version.workspace = true
bip32.workspace = true
camino.workspace = true
clap.workspace = true
codespan-reporting.workspace = true
datatest-stable.workspace = true
futures.workspace = true
http.workspace = true
im.workspace = true
inquire.workspace = true
json_to_table.workspace = true
miette.workspace = true
num-bigint.workspace = true
prometheus.workspace = true
rand.workspace = true
regex.workspace = true
reqwest.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
serde.workspace = true
shlex.workspace = true
signature.workspace = true
tabled.workspace = true
tap.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
uuid.workspace = true
url.workspace = true

rtd-config.workspace = true
rtd-bridge.workspace = true
rtd-data-store.workspace = true
rtd-execution.workspace = true
rtd-faucet.workspace = true
rtd-futures.workspace = true
rtd-swarm-config.workspace = true
rtd-indexer-alt.workspace = true
rtd-indexer-alt-framework.workspace = true
rtd-indexer-alt-graphql.workspace = true
rtd-indexer-alt-consistent-store.workspace = true
rtd-indexer-alt-reader.workspace = true
rtd-pg-db.workspace = true
rtd-genesis-builder.workspace = true
rtd-types.workspace = true
rtd-json.workspace = true
rtd-swarm.workspace = true
rtd-json-rpc-types.workspace = true
rtd-sdk.workspace = true
rtd-keys.workspace = true
rtd-source-validation.workspace = true
rtd-move.workspace = true
rtd-move-build.workspace = true
rtd-package-alt.workspace = true
rtd-package-management.workspace = true
rtd-protocol-config.workspace = true
shared-crypto.workspace = true
rtd-transaction-builder.workspace = true
move-binary-format.workspace = true
move-trace-format.workspace = true
move-bytecode-source-map.workspace = true
linku-common.workspace = true
test-cluster.workspace = true
rtd-replay-2.workspace = true

fastcrypto.workspace = true
fastcrypto-zkp.workspace = true

rustyline.workspace = true
rustyline-derive.workspace = true
colored.workspace = true
unescape.workspace = true
shell-words.workspace = true

tempfile.workspace = true
telemetry-subscribers.workspace = true

move-analyzer.workspace = true
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-package-alt.workspace = true
move-package-alt-compilation.workspace = true
move-compiler.workspace = true
csv.workspace = true
move-vm-profiler.workspace = true
move-vm-config.workspace = true
move-ir-types.workspace = true
move-command-line-common.workspace = true
move-cli.workspace = true
move-symbol-pool.workspace = true
normalize-line-endings = "0.3.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemalloc-ctl.workspace = true

[dev-dependencies]
prometheus.workspace = true
fs_extra.workspace = true
expect-test.workspace = true
assert_cmd.workspace = true
toml.workspace = true
insta.workspace = true
insta-cmd.workspace = true
toml_edit.workspace = true

test-cluster.workspace = true
rtd-macros.workspace = true
rtd-simulator.workspace = true
rtd-test-transaction-builder.workspace = true
rtd-protocol-config.workspace = true
serde_json.workspace = true

[target.'cfg(msim)'.dependencies]
msim.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = ["tikv-jemalloc-ctl"]

[[example]]
name = "generate-genesis-checkpoint"
path = "src/generate_genesis_checkpoint.rs"
test = false

[[test]]
name = "ptb_files_tests"
harness = false

[[test]]
name = "shell_tests"
harness = false

[features]
tracing = [
    "rtd-types/tracing",
    "rtd-execution/tracing",
    "rtd-move/tracing",
    "rtd-replay-2/tracing",
]
