[package]
name = "RtdSystem"
version = "0.0.1"
published-at = "0x3"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
Rtd = { local = "../rtd-framework" }

[addresses]
rtd_system = "0x3"
