---
version: "3.9"
services:
  rosetta-online:
    image: linku/rtd-rosetta-devnet
    ports:
      - "9002:9002"
    expose:
      - "9002"
    volumes:
      - data:/data:rw
    working_dir: /rtd/devnet
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/rtd-rosetta generate-rosetta-cli-config --env devnet &
        /usr/local/bin/rtd-rosetta start-online-server --env devnet --node-config fullnode.yaml
    stdin_open: true
    tty: true
  rosetta-offline:
    image: linku/rtd-rosetta-devnet
    ports:
      - "9003:9003"
    expose:
      - "9003"
    working_dir: /rtd/devnet
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/rtd-rosetta start-offline-server --env devnet
    stdin_open: true
    tty: true
volumes:
  data:
