[package]
name = "rtd-rpc-resolver"
version.workspace = true
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
bcs.workspace = true
futures.workspace = true
lru.workspace = true
move-core-types.workspace = true
serde.workspace = true
serde_json.workspace = true
rtd-package-resolver.workspace = true
rtd-rpc-api.workspace = true
rtd-types.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
