[package]
name = "rtd-replay"
version = "0.1.0"
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
bcs.workspace = true
prometheus.workspace = true
async-trait.workspace = true
jsonrpsee.workspace = true
async-recursion.workspace = true
clap = { version = "4.1.4", features = ["derive"] }
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
similar.workspace = true
thiserror.workspace = true
tracing.workspace = true
rand.workspace = true
lru.workspace = true
parking_lot.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
shellexpand.workspace = true
tempfile.workspace = true
http.workspace = true

move-vm-config.workspace = true
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-core-types.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tabled.workspace = true
regex.workspace = true

shared-crypto.workspace = true
rtd-config.workspace = true
rtd-core.workspace = true
rtd-execution.workspace = true
rtd-framework.workspace = true
rtd-json-rpc-api.workspace = true
rtd-json-rpc-types.workspace = true
rtd-protocol-config.workspace = true
rtd-sdk.workspace = true
rtd-storage.workspace = true
rtd-transaction-checks.workspace = true
rtd-types.workspace = true
