[package]
name = "rtd-transaction-builder"
version = "0.0.0"
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
bcs.workspace = true

move-binary-format.workspace = true
rtd-json-rpc-types.workspace = true
rtd-types.workspace = true
rtd-json.workspace = true
rtd-protocol-config.workspace = true

move-core-types.workspace = true
