[package]
name = "rtd-network"
version = "0.0.0"
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
anemo.workspace = true
anemo-tower.workspace = true
governor.workspace = true
serde.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
dashmap.workspace = true
tower.workspace = true
shared-crypto.workspace = true
eyre.workspace = true
http.workspace = true
tokio-rustls.workspace = true
tonic-health.workspace = true
tower-http.workspace = true
rtd-http.workspace = true
rtd-tls.workspace = true

rtd-macros.workspace = true
rtd-storage.workspace = true
rtd-types.workspace = true
rtd-config.workspace = true
rtd-swarm-config.workspace = true
rtd-simulator.workspace = true
rtd-protocol-config.workspace = true
rtd-data-ingestion-core.workspace = true

arc-swap.workspace = true
bcs.workspace = true
bytes.workspace = true
fastcrypto.workspace = true
fastcrypto-tbls.workspace = true
linku-common.workspace = true
linku-network.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
futures.workspace = true
tap.workspace = true
rand.workspace = true
anyhow.workspace = true
prometheus.workspace = true
linku-metrics.workspace = true

[build-dependencies]
anemo-build.workspace = true
tonic-build.workspace = true

[dev-dependencies]
rtd-macros.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["test-util"] }
ed25519-consensus.workspace = true
tempfile = "3.3.0"
