[package]
name = "Locked Stake"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Rtd = { local = "../../../crates/rtd-framework/packages/rtd-framework" }
RtdSystem = { local = "../../../crates/rtd-framework/packages/rtd-system" }

[addresses]
locked_stake = "0x0"
