[package]
name = "reviews_rating"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Rtd = { local = "../../../crates/rtd-framework/packages/rtd-framework", override = true }

[addresses]
reviews_rating =  "0x0"
