[package]
name = "rtd-node"
version.workspace = true
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
anemo.workspace = true
anemo-tower.workspace = true
antithesis_sdk.workspace = true
arc-swap.workspace = true
axum.workspace = true
anyhow.workspace = true
base64.workspace = true
bcs.workspace = true
clap.workspace = true
consensus-core.workspace = true
prometheus.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
futures.workspace = true
parking_lot.workspace = true
tower.workspace = true
tower-http.workspace = true
http.workspace = true
reqwest.workspace = true
tap.workspace = true
serde.workspace = true
bin-version.workspace = true
url.workspace = true
humantime.workspace = true

rtd-tls.workspace = true
rtd-macros.workspace = true
rtd-config.workspace = true
rtd-core.workspace = true
rtd-rpc-api.workspace = true
rtd-storage.workspace = true
rtd-name-service.workspace = true
rtd-network.workspace = true
rtd-json-rpc.workspace = true
rtd-json-rpc-api.workspace = true
rtd-protocol-config.workspace = true
rtd-snapshot.workspace = true
rtd-telemetry.workspace = true
rtd-types.workspace = true
linku-metrics.workspace = true
linku-service.workspace = true
linku-common.workspace = true
linku-network.workspace = true
typed-store.workspace = true
telemetry-subscribers.workspace = true
fastcrypto.workspace = true
fastcrypto-zkp.workspace = true
move-vm-config.workspace = true
rtd-http.workspace = true
rtd-metrics-push-client.workspace = true

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { workspace = true, optional = true, features = ["profiling", "disable_initial_exec_tls"] }

[target.'cfg(msim)'.dependencies]
rtd-simulator.workspace = true

[features]
default = ["jemalloc"]
jemalloc = ["tikv-jemallocator"]
