[package]
name = "nft_rental"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Rtd = { local = "../../../crates/rtd-framework/packages/rtd-framework", override = true }
Kiosk = { git = "https://github.com/LinkUVerse/apps.git", subdir = "kiosk", rev = "testnet" }

[addresses]
nft_rental = "0x0"
