[package]
name = "rtd-package-dump"
version.workspace = true
authors = ["LinkU Labs <build@linkulabs.com"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
bcs.workspace = true
cynic.workspace = true
fastcrypto.workspace = true
move-core-types.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
rtd-types.workspace = true
tracing.workspace = true

[build-dependencies]
cynic-codegen.workspace = true
