[package]
name = "rtd-simulator"
version = "0.7.0"
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
move-package-alt.workspace = true
move-package-alt-compilation.workspace = true
linku-network.workspace = true
rtd-framework.workspace = true
rtd-move-build.workspace = true
rtd-types.workspace = true
tempfile.workspace = true
tracing.workspace = true
anemo.workspace = true
anemo-tower.workspace = true
fastcrypto = { workspace = true, features = ["copy_key"] }
telemetry-subscribers.workspace = true
tower.workspace = true
lru.workspace = true
rand.workspace = true
serde.workspace = true
bcs.workspace = true

[target.'cfg(msim)'.dependencies]
msim.workspace = true
