[package]
name = "rtd-light-client"
version.workspace = true
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "rtd-light-client"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
thiserror.workspace = true
bcs.workspace = true
bytes.workspace = true
clap.workspace = true
move-core-types.workspace = true
roaring.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["full"] }
serde_yaml.workspace = true
serde_json.workspace = true
rtd-data-ingestion-core.workspace = true
rtd-types.workspace = true
rtd-config.workspace = true
rtd-rpc-api.workspace = true
rtd-sdk.workspace = true
move-binary-format.workspace = true
rtd-json-rpc-types.workspace = true
rtd-package-resolver.workspace = true
rtd-storage.workspace = true
url.workspace = true
reqwest.workspace = true
tracing.workspace = true
object_store.workspace = true
env_logger = "0.11.5"
log = "0.4.22"
tempfile = "3.8.0"
fastcrypto.workspace = true

[dev-dependencies]
tempfile.workspace = true
