[package]
name = "usdc_usage"
edition = "2024.beta"

[dependencies]
Rtd = { override = true, local = "../../../crates/rtd-framework/packages/rtd-framework" }
usdc = { git = "https://github.com/circlefin/stablecoin-rtd.git", subdir = "packages/usdc", rev = "master" }


[addresses]
usdc_usage = "0x0"