[package]
name = "shared-with-tto"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Rtd = { local = "../../../../crates/rtd-framework/packages/rtd-framework" }
common = { local = "../common" }

[addresses]
shared_with_tto = "0x0"
