[package]
name = "rtd-indexer-alt-schema"
version.workspace = true
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
diesel = {workspace = true, features = ["postgres_backend", "chrono"]}
diesel_migrations.workspace = true
serde.workspace = true
bcs.workspace = true

rtd-field-count.workspace = true
rtd-protocol-config.workspace = true
rtd-types.workspace = true
