---
version: "3.9"
services:
  rtd-network:
    image: linku/rtd-rosetta-local
    ports:
      - "9000:9000"
    expose:
      - "9000"
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/rtd start
  rosetta-online:
    image: linku/rtd-rosetta-local
    ports:
      - "9002:9002"
    expose:
      - "9002"
    working_dir: /rtd/localnet
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/rtd-rosetta generate-rosetta-cli-config &
        /usr/local/bin/rtd-rosetta start-online-remote-server --full-node-url http://rtd-network:9000
    stdin_open: true
    tty: true
  rosetta-offline:
    image: linku/rtd-rosetta-local
    ports:
      - "9003:9003"
    expose:
      - "9003"
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/rtd-rosetta start-offline-server