[package]
name = "BridgedETH"
version = "0.0.1"
edition = "legacy"

[dependencies]
MoveStdlib = { local = "../../../../crates/rtd-framework/packages/move-stdlib" }
Rtd = { local = "../../../../crates/rtd-framework/packages/rtd-framework" }

[addresses]
bridged_eth = "0x0"
