[package]
name = "rtd-source-validation"
version.workspace = true
authors = ["LinkU Labs <build@linkulabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
colored.workspace = true
flate2.workspace = true
futures.workspace = true
serde.workspace = true
tar.workspace = true
tempfile.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true
ureq.workspace = true

rtd-json-rpc-types.workspace = true
rtd-move-build.workspace = true
rtd-package-management.workspace = true
rtd-package-alt.workspace = true
rtd-types.workspace = true
rtd-sdk.workspace = true

move-binary-format.workspace = true
move-bytecode-source-map.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-package-alt.workspace = true
move-package-alt-compilation.workspace = true
move-symbol-pool.workspace = true

[dev-dependencies]
datatest-stable.workspace = true
expect-test.workspace = true
fs_extra.workspace = true
insta.workspace = true
insta-cmd.workspace = true
rand.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "test-util"] }
tracing.workspace = true

rtd-config.workspace = true
rtd-test-transaction-builder.workspace = true
test-cluster.workspace = true

[target.'cfg(msim)'.dependencies]
msim.workspace = true

[[test]]
name = "shell_tests"
harness = false


