name: Trigger pre-build images for Rtd commits

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
      - 'devnet'
      - 'testnet'
      - 'mainnet'
      - 'releases/rtd-*-release'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prebuild-rtd-images:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Pre-build Images in LinkUVerse/rtd-operations
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # pin@v3.0.0
        with: 
          repository: LinkUVerse/rtd-operations
          token: ${{ secrets.DOCKER_BINARY_BUILDS_DISPATCH }}
          event-type: prebuild-rtd-images
          client-payload: >
            {
              "rtd_commit": "${{ github.sha }}",
              "caller_name": "rtd_repo_${{ github.ref_name }}",
              "push_to_dockerhub": true,
              "build_arm64": ${{ github.ref_name != 'main' && (github.ref_name == 'devnet' || github.ref_name == 'testnet' || github.ref_name == 'mainnet' || (startsWith(github.ref_name, 'releases/rtd-') && endsWith(github.ref_name, '-release'))) }},
              "graphql_rpc": true,
              "indexer_alt": true,
              "stress": true
            }
