name: Trigger Release binaries builds

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'devnet'
      - 'testnet'
      - 'mainnet'
      - 'releases/rtd-*-release'

concurrency: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  release-binaries:
    name: Trigger Release binaries builds
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Release binaries builds in LinkUVerse/rtd-operations
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # pin@v3.0.0
        with:
          repository: LinkUVerse/rtd-operations
          token: ${{ secrets.DOCKER_BINARY_BUILDS_DISPATCH }}
          event-type: build-release-binaries
          client-payload: '{"rtd_commit": "${{ github.sha }}"}'

  # Tag all rtd images with branch name, so that they can be easily found
  tag-docker-hub-images:
    name: Tag rtd docker images in DockerHub
    if: github.event_name == 'push' && contains(fromJSON('["devnet", "testnet", "mainnet"]'), github.ref_name)
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Tagging of images in DockerHub, in LinkUVerse/rtd-operations
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # pin@v3.0.0
        with:
          repository: LinkUVerse/rtd-operations
          token: ${{ secrets.DOCKER_BINARY_BUILDS_DISPATCH }}
          event-type: tag-docker-images
          client-payload: '{"rtd_commit": "${{ github.sha }}", "tag": "${{ github.ref_name }}"}'
