[package]
name = "rtd-verifier-latest"
version = "0.1.0"
edition = "2024"
authors = ["LinkU Labs <eng@linkulabs.com>"]
description = "Move framework for Rtd platform"
license = "Apache-2.0"
publish = false

[dependencies]
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true
move-abstract-stack.workspace = true

move-bytecode-verifier = { path = "../../../external-crates/move/crates/move-bytecode-verifier" }

rtd-types.workspace = true
rtd-protocol-config.workspace = true
